export const UnitsOptions = [
  {value: 'kg', label: 'kg'},
  {value: 'g', label: 'g'},
  {value: 'mg', label: 'mg'},
  {value: 'box', label: 'box'},
  {value: 'pack', label: 'pack'},
  {value: 'pair', label: 'pair'},
  {value: 'bag', label: 'bag'},
  {value: 'cm', label: 'cm'},
  {value: 'feet', label: 'feet'},
  {value: 'in', label: 'in'},
  {value: 'lb', label: 'lb'},
  {value: 'yard', label: 'yard'},
  {value: 'portion', label: 'portion(s)'},
  {value: 'bowl', label: 'bowl'},
  {value: 'bottle', label: 'bottle'},
  {value: 'plate', label: 'plate'},
  {value: 'carton', label: 'carton'},
];
